AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "Webaverse Service Secrets"

 Parameters:
    DockerHubCredentialsUsername:
        Type: String
        Default: username
        Description: DockerHub username to pull down Docker images
    DockerHubCredentialsPassword:
        Type: String
        NoEcho: true
        Default: password
        Description: DockerHub password to pull down Docker images
    GitHubPersonalAccessToken:
        Type: String
        NoEcho: true
        Default: password
        Description: GitHub Personal Access Token to access changes to the repos
Resources:
    DockerHubSecretAccessPolicy:
        Type: "AWS::IAM::Policy"
        Properties:
            PolicyDocument: !Sub |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "secretsmanager:GetSecretValue"
                            ],
                            "Resource": [
                                "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DockerHub*"
                            ]
                        }
                    ]
                }
            Roles: 
              - !Ref CodeBuildServiceRole
            PolicyName: "dockerhub_secret_access"

    DockerHubSecretsManagerSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "DockerHubCredentialsSecret-${AWS::Region}"
            SecretString: '{"username":DockerHubCredentialsUsername,"password":DockerHubCredentialsPassword}'

    GitHubPATSecretsManagerSecret:
        Type: "AWS::SecretsManager::Secret"
        Properties:
            Name: !Sub "GitHubPATSecretsManagerSecret-${ServiceName}-${AWS::Region}"
            SecretString: '{"personalaccesstoken":GitHubPersonalAccessToken}'

    