AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "Webaverse Service Network"

Resources:
    EC2VPC:
        Type: "AWS::EC2::VPC"
        Properties:
            CidrBlock: "10.10.0.0/16"
            EnableDnsSupport: true
            EnableDnsHostnames: true
            InstanceTenancy: "default"
            Tags:
            -   Key: "Name"
                Value: !Sub "Webaverse-Services"

    EC2SubnetA:
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}a"
            CidrBlock: "10.10.0.0/20"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: true
            Tags: 
            -   Key: "Name"
                Value: !Sub "Webaverse-Services-SubnetA"

    EC2SubnetB:
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}b"
            CidrBlock: "10.10.16.0/20"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: true
            Tags: 
            -   Key: "Name"
                Value: !Sub "Webaverse-Services-SubnetB"

    EC2SubnetC:
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}c"
            CidrBlock: "10.10.32.0/20"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: true
            Tags:
            -   Key: "Name"
                Value: !Sub "Webaverse-Services-SubnetC"

    ECSCluster:
        Type: "AWS::ECS::Cluster"
        Properties:
            ClusterName: !Sub "ECSCluster-${AWS::Region}"
            CapacityProviders: 
              - "FARGATE_SPOT"
              - "FARGATE"
Outputs:
    StackVPC:
        Description: The ID of the stack VPC
        Value: !Ref EC2VPC
        Export:
            Name: !Sub "${AWS::StackName}-VPCID"
    StackSubnetA:
        Description: The ID of the stack SubnetA
        Value: !Ref EC2SubnetA
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetA"
    StackSubnetAAZ:
        Description: The AvailabilityZone of the stack SubnetA
        Value: !GetAtt EC2SubnetA.AvailabilityZone
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetA-AZ"
    StackSubnetB:
        Description: The ID of the stack SubnetB
        Value: !Ref EC2SubnetB
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetB"
    StackSubnetBAZ:
        Description: The AvailabilityZone of the stack SubnetB
        Value: !GetAtt EC2SubnetB.AvailabilityZone
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetB-AZ"
    StackSubnetC:
        Description: The ID of the stack SubnetC
        Value: !Ref EC2SubnetC
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetC"
    StackSubnetCAZ:
        Description: The AvailabilityZone of the stack SubnetC
        Value: !GetAtt EC2SubnetC.AvailabilityZone
        Export:
            Name: !Sub "${AWS::StackName}-EC2SubnetC-AZ"
    StackECSCluster:
        Description: The ID of the stack ECSCluster
        Value: !Ref ECSCluster
        Export:
            Name: !Sub "${AWS::StackName}-ECSCluster"
    
        